server:
  port: 9091
spring:
  application:
    name: oauth-server
security:
  jwt:
    secret: RkL+xbQRNWuHdgfd8AZ0Urps8mR+894/aEqlzL/iI1LoPpbLSlhy9oNkDQgyIS0Rz9OQHAcUug6urdjePLWVOg==  # Replace with a strong, unique key
    issuer: "http://localhost:9091/oauth/token"