server:
  port: 9091
spring:
  active:
    profile: dev
  application:
    name: oauth-server
security:
  jwt:
    secret: ${JWT_SECRET}  # Replace with a strong, unique key
    issuer: ${OAUTH_ISSUER}